### ISSUE TITLE
Screen does not scroll when keyboard appears

### ISSUE THREAD

**Issue by 2dvisio** [Mobistudy/Mobistudyapp#10]
When registering a new user and reaching the end of the list of fields (eg. conditions / medications) the keyboard hides the form.

Trying to scroll the page up does not work.

**Comment by dariosalviwork** [comment]
[this ](https://github.com/cjpearson/cordova-plugin-keyboard) may solve it.
There was a [KeyboardShrinksView in previous versions of cordova](https://cordova.apache.org/docs/en/3.0.0/guide/platforms/ios/config.html), but looks like it has disappeared?

**Comment by dariosalviwork** [comment]
It seems that now it's done [this way](https://stackoverflow.com/questions/21739396/phonegap-3-3-ios-keyboardshrinksview).

**Comment by dariosalviwork** [comment]
interesting, you needed to revert to a previous version of cordova 4 ios?
is it documented somewhere?

**Comment by jamtholee** [comment]
No, the fix was changing the viewport meta in the base template.

The ios version was me trying to force cordova to use a more up to date one, because for some reason it was automatically installing 0.0.1 (https://github.com/Mobistudy/Mobistudyapp/commit/9a89123aa8f122884387d17a81a15e185e8c2b06)
