### ISSUE TITLE
Profile: User must enter profile details *twice* to receive study proposals

### ISSUE THREAD

**Issue by Assimilate** [Mobistudy/Mobistudyapp#100]
If the profile details are not entered (after registration, again, using update button) (language, country etc...) the query for the studies will not filter for any studies. For some reason the participant information is not registered in the database upon registration of a user but only on updating the profile.

**Comment by dariosalvi78** [comment]
isn't the info in the profile mandatory?

**Comment by Assimilate** [comment]
@dariosalvi78  It is as far as i know. But it is the fact that it needs to be sent *again* that is causing the issue.

**Comment by dariosalvi78** [comment]
again? when?

**Comment by Assimilate** [comment]
Voluntarily using the profile update button. I realise this issue may have not been well described, maybe we can chat verbally and its easier to explain.
