### ISSUE TITLE
UX: Permission access

### ISSUE THREAD

**Issue by Assimilate** [Mobistudy/Mobistudyapp#101]
Assume that:

The study contains these two tasks:

1) QCST -> Requires Pedometer permission
2) SMWT -> Requires Pedometer permission and GPS permission

If the permission for the pedometer in 1) is already given -> 2) should not prompt the user for the same  pedometer permission again.

**Comment by dariosalvi78** [comment]
there is no way to ask the phone if permissions were given, at least not in iPhone. The app should keep the state of this but it's a bit flaky. I'd prefer to leave it as it is for now.
