### ISSUE TITLE
Add prev and next button under/in carousel when introducing a task.

### ISSUE THREAD

**Issue by dariosalvi78** [Mobistudy/Mobistudyapp#103]
Not everyone understands that it can be swiped.
This should be added similarly for all tasks.

**Comment by Assimilate** [comment]
We have several alternatives available:

https://quasar.dev/vue-components/carousel

I prefer the arrows on the left and right. But we can have buttons too if you think that looks better.

Do we want to keep the round navigation icons that looks like the "loading" spinner? We can change the shape of these two to make it more obvious they are do not represent "loading."

**Comment by dariosalvi78** [comment]
arrows are nice, yes
