### ISSUE TITLE
App hangs if user registers but doesn't complete profile

### ISSUE THREAD

**Issue by jamtholee** [Mobistudy/Mobistudyapp#12]
OS: iOS

Steps to reproduce:

1. Register new user
2. Click through until page which asks for user's name, dob, medication etc.
3. Quit the app (close from multitasking too)
4. Go back into the app

What happens:
- App logs user in, but can't fetch profile, so just displays the loading animation indefinitely

Source of issue:
`serverAPI.js`:
```
export async function getProfile (userKey) {
  const resp = await axios.get(BASE_URL + '/participants/byuserkey/' + userKey, axiosConfig)
  return resp.data
}
```

Hangs on axios.get

**Comment by dariosalviwork** [comment]
probably a bug on the server

**Comment by arvgo** [comment]
This is a minor issue and will be left on the backlog.

**Comment by dariosalviwork** [comment]
OK, now I understand what this means.
Yes, the registration of a participant goes into 2 steps. We joined them in the interface, but they should actually be separated.

Considering the UI issues with the disease and the meds I believe that the onboarding must be split into different pages with clearer instructions. This will also allow a better management of edge cases like the one mentioned here.
