### ISSUE TITLE
Stuck in the finished study page

### ISSUE THREAD

**Issue by 2dvisio** [Mobistudy/Mobistudyapp#18]
![image](https://user-images.githubusercontent.com/925236/53332387-27efae80-38eb-11e9-8663-31f80d6e8c9e.png)
Latest push on the repo of the app. I am having this issue.
The app gets stuck in that screen

**Comment by 2dvisio** [comment]
![image](https://user-images.githubusercontent.com/925236/53332418-3a69e800-38eb-11e9-887d-97575bbb5cbd.png)

**Comment by arvgo** [comment]
Tested and could not replicate issue with latest API (07-Mar-2018). Closing issue.
