### ISSUE TITLE
6MWT - Implement path/stroke on map

### ISSUE THREAD

**Issue by elinforsnor** [Mobistudy/Mobistudyapp#55]
Implemented according to Google Maps documentation, but needs to be tested when there's a API-key with enabled billing.

**Comment by dariosalvi78** [comment]
there is currently a marked on where your position is and it's working. An improvement could be a trace instead of a marker. Here is a guide: https://stackoverflow.com/questions/51816751/draw-lines-between-multiple-markers-on-google-map-using-java-script
