### ISSUE TITLE
Add task icon above heading on task pages

### ISSUE THREAD

**Issue by palladog** [Mobistudy/Mobistudyapp#77]
Add task icon above the task heading (see example below). 

<img width="200" alt="Skärmavbild 2020-10-28 kl  13 22 15" src="https://user-images.githubusercontent.com/31319905/97435544-d6e65800-1920-11eb-8bd2-05fa8aef0ede.png">

*Reasoning:* In "Today's Tasks", each task has a corresponding icon, and it would be good to strengthen these iconic relationships in the task pages as well. It would also help the user to know what task they are in, especially if that task is text heavy.

**Comment by dariosalvi78** [comment]
OK, it's a good idea. Actually it could include the task name as well and the "Close X" could become just an X or just a "Close". Make sure it renders fine on smaller screens!
