### ISSUE TITLE
Make Consents into a component and remove the "Grant Access" Button

### ISSUE THREAD

**Issue by af9593** [Mobistudy/Mobistudyapp#80]
**Usability:** Remove the "GRANT ACCESS" button, so that the user only checks the checkbox and is then prompted to provide access
**Consistency:** Create a component to solve the inconsistency in code between (StudyConfig and ConsentsItems)

**Comment by dariosalvi78** [comment]
the idea is that, instead of having this separate button, when the user clicks on the checkbox the authorization process is launched (same as with the button) and the checkbox doesn't get ticked until the process has completed successfully.
