### ISSUE TITLE
Conditions field impossible to fill in iOS

### ISSUE THREAD

**Issue by 2dvisio** [Mobistudy/Mobistudyapp#9]
To recreate the issue:

1. Register a new user on the app (tested only on iOS)
2. reach the conditions field
3. type anything (e.g. backac....)
4. try to see the whole menu of items and select one
5. realise that you cannot scroll and that the dropdown menu disappears

This might be a Quasar bug :/

**Comment by jamtholee** [comment]
Merged into #10
